api = "0.2"

[buildpack]
id = "heroku/ruby"
version = "0.1.4"
name = "Ruby"
homepage = "https://github.com/heroku/heroku-buildpack-ruby"
ruby_version = "2.4.10"

[publish]

[publish.Ignore]
files = ["spec/"]

[[publish.Vendor]]
url = "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.10.tar.gz"
dir = "vendor/ruby/heroku-20"

[[publish.Vendor]]
url = "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.10.tar.gz"
dir = "vendor/ruby/heroku-22"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack"
